---
services:
  pyroscope:
    image: grafana/pyroscope
    restart: always
    hostname: pyroscope
    ports:
      - 4040:4040
    networks:
      - metrics
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - metrics
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    restart: always
    networks:
      - metrics
    depends_on:
      - pushgateway
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus
  pushgateway:
    image: prom/pushgateway
    hostname: pushgateway
    ports:
      - 9091:9091
    restart: always
    networks:
      - metrics
networks:
  metrics:
